apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: s3-access-sa
      containers:
        - name: backend
          image: 257394477599.dkr.ecr.us-east-1.amazonaws.com/image-app-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: S3_BUCKET
              value: image-upload-bucket-dev-20250719

---
apiVersion: v1
kind: Service
metadata:
  name: backend 
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP